apiVersion: v1
kind: ServiceAccount
metadata:
  name: logtrain
  namespace: akkeris-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logtrain
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - pods
  - configmaps
  - services
  - namespaces
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logtrain-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logtrain
subjects:
- kind: ServiceAccount
  name: logtrain
  namespace: akkeris-system