apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logtrain
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - logtrain
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - pods
  - configmaps
  - services
  - namespaces
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch