apiVersion: v1
kind: Service
metadata:
  name: logtail
  labels:
    name: logtail
spec:
  ports:
  - port: 80
    name: web
    protocol: TCP
    targetPort: 9000
  - port: 9002
    name: syslogtcp
    protocol: TCP
    targetPort: 9002
  clusterIP: None
  selector:
    name: logtail