{
 "title": "Logtrain Metrics (MARU)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Space", "query": "akkeris-system" },
   { "name": "container", "label": "Application", "query": "logtrain" }
  ]
 },
 "panels": [
  {
   "title": "Outbound Send Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logtrain_errors[5m]) / rate(logtrain_errors_count[5m])",
     "legendFormat": "{{syslog}}"
    }
   ]
  },
  {
   "title": "Outbound Sent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logtrain_packets_sent_sum[2m]) / rate(logtrain_packets_sent_count[2m])",
     "legendFormat": "{{syslog}}"
    }
   ]
  },
  {
   "title": "Outbound Pressure",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(logtrain_pressure_sum[5m]) / rate(logtrain_pressure_count[5m])",
     "legendFormat": "{{kubernetes_pod_name}} - {{syslog}}"
    }
   ]
  },
  {
   "title": "Outbound Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logtrain_connections_sum[5m]) / rate(logtrain_connections_count[5m])",
     "legendFormat": " {{syslog}}"
    }
   ]
  },
  {
   "title": "Deadpackets (no route)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logtrain_deadpackets_sum[2m]) / rate(logtrain_deadpackets_count[2m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_pod_name=~\"$container.*\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Go Threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{kubernetes_pod_name=~\"$container.*\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{container=\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_file_descriptors{container=\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Filesystem Writes/Reads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_fs_writes_bytes_total{container=\"$container\", namespace=\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "{{pod}} writes"
    },
    {
     "expr": "sum(increase(container_fs_reads_bytes_total{container=\"$container\", namespace=\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "{{pod}} reads"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, container, namespace) (rate(container_cpu_usage_seconds_total{ container=\"$container\",namespace=\"$namespace\", image!=\"\",container!=\"POD\"}[5m])) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(container_memory_usage_bytes{container=\"$container\",namespace=\"$namespace\",name!~\"POD\"}) by (pod,instance)",
     "legendFormat": "{{pod}}"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "avg(container_memory_usage_bytes{container=\"$container\",namespace=\"$namespace\",name!~\"POD\"})",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Memory Limits and Faults",
   "type": "graph",
   "description": "This counter is increased each time memory allocation fails — that is, each time the pre-set memory limit is hit. Thus, spikes in this metric indicate one or more containers needing more memory than was allocated.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short", "label": "Memory" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(rate(container_memory_failures_total{namespace=\"$namespace\",pod=~\"$container.*\",container!=\"POD\",failure_type=\"pgfault\"}[1m])) by (pod)",
     "legendFormat": "{{pod}} - Page Faults"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(rate(container_memory_failures_total{namespace=\"$namespace\",pod=~\"$container.*\",container!=\"POD\",failure_type=\"pgmajfault\"}[1m])) by (pod)",
     "legendFormat": "{{pod}} - Page Faults (Swapping Code to Disk)"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "container_memory_failcnt{namespace=\"$namespace\",pod=~\"$container.*\"}",
     "legendFormat": "{{pod}} - Memory Limit Hit"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(increase(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$container.*\"}[1m]))",
     "legendFormat": "Transmitted Bytes"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(increase(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$container.*\"}[1m]))",
     "legendFormat": "Received Bytes"
    }
   ]
  },
  {
   "title": "Network Sockets",
   "type": "graph",
   "description": "The amount of open TCP/UDP sockets listening to or using a socket.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "container_sockets{namespace=\"$namespace\",pod=~\"$container.*\",image!~\"rancher/pause.*\",image!=\"\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "short", "label": "Memory" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(increase(container_network_transmit_packets_dropped_total{namespace=\"$namespace\",pod=~\"$container.*\"}[5m]))",
     "legendFormat": "Transmit Packets Dropped"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(increase(container_network_transmit_errors_total{namespace=\"$namespace\",pod=~\"$container.*\"}[5m]))",
     "legendFormat": "Transmit Errors"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(increase(container_network_receive_packets_dropped_total{namespace=\"$namespace\",pod=~\"$container.*\"}[5m]))",
     "legendFormat": "Receive Packets Dropped"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(increase(container_network_receive_errors_total{namespace=\"$namespace\",pod=~\"$container.*\"}[5m]))",
     "legendFormat": "Receive Errors"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "short", "label": "Memory" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(container_threads{container=\"$container\",namespace=\"$namespace\"}) by (pod,instance)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}