name: Publish Docker
on: 
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Replace ref in daemonset
      run: sed -E -i 's/logtrain:v[0-9]+\.[0-9]+\.[0-9]+/logtrain\:$GITHUB_REF/g' deployments/kubernetes/logtrain-daemonset.yaml
    - uses: github-actions-x/commit@v2.6
      with:
        commit-message: update daemonset image
        push-branch: main
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: akkeris/logtrain
        username: ${{ secrets.DockerUser }}
        password: ${{ secrets.DockerPassword }}
        tag_names: true
